#!/usr/bin/python3
def raise_exception():
    a = "aaa"
    print(a / 2)
